version: "3.8"

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=drone_dashboard
      - JWT_SECRET=your_jwt_secret
    volumes:
      - ./server:/app
    restart: always

  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: drone_dashboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
